# Service Account для специалиста по ИБ
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-admin-sa
  namespace: propdevelopment-security
  labels:
    app.kubernetes.io/name: propdevelopment-rbac
    app.kubernetes.io/component: security-admin
    app.kubernetes.io/managed-by: manual
    role: security-admin
---
# Service Account для DevOps инженера
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-engineer-sa
  namespace: default
  labels:
    app.kubernetes.io/name: propdevelopment-rbac
    app.kubernetes.io/component: devops-engineer
    app.kubernetes.io/managed-by: manual
    role: devops-engineer
---
# Service Account для второго DevOps инженера
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops2-sa
  namespace: default
  labels:
    app.kubernetes.io/name: propdevelopment-rbac
    app.kubernetes.io/component: devops-engineer
    app.kubernetes.io/managed-by: manual
    role: devops-engineer
---
# Service Account для разработчика
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-sa
  namespace: propdevelopment-dev
  labels:
    app.kubernetes.io/name: propdevelopment-rbac
    app.kubernetes.io/component: developer
    app.kubernetes.io/managed-by: manual
    role: developer
---
# Service Account для второго разработчика
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer2-sa
  namespace: propdevelopment-dev
  labels:
    app.kubernetes.io/name: propdevelopment-rbac
    app.kubernetes.io/component: developer
    app.kubernetes.io/managed-by: manual
    role: developer
---
# Service Account для viewer (менеджеры, аналитики)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer-sa
  namespace: default
  labels:
    app.kubernetes.io/name: propdevelopment-rbac
    app.kubernetes.io/component: cluster-viewer
    app.kubernetes.io/managed-by: manual
    role: cluster-viewer
