apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: security-admin
  labels:
    app.kubernetes.io/name: propdevelopment-rbac
    app.kubernetes.io/component: security-admin-role
    app.kubernetes.io/managed-by: manual
rules:
# Полные права администратора для специалиста по ИБ
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]
